# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3.8

repos:
  # require : pre-commit install --hook-type commit-msg
  - repo: local
    hooks:
      - id: jira-ticket
        name: "Add ticket number in commit message."
        language: pygrep
        entry: '\A(?!(SKIL|MAT|TRSE)-[0-9]{2,}|Merge branch)'
        args: [ --multiline ]
        stages: [ commit-msg ]

  - repo: https://github.com/asottile/reorder_python_imports
    rev: "v1.7.0"
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: flake8
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.812'   # 20 Feb 2021
    hooks:
    - id: mypy
#      additional_dependencies: [ tokenize-rt==3.2.0 ]

#  - repo: https://github.com/atugushev/pip-tools
#    rev:  b8130a0c1ca5379334c8be21074f9c15cc54d035
#    hooks:
#    - id: pip-compile
